<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/02/25 23:10:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'JJ86072a16m0',
  'name' => 'doctrine',
)),);
